/*======================================================================

   font_16x16 texture coordinates
   Generated by Rel Texture Packer
   relminator 2010

======================================================================*/


#ifndef FONT_16X16__H
#define FONT_16X16__H


#define FONT_16X16_BITMAP_WIDTH   64
#define FONT_16X16_BITMAP_HEIGHT  512
#define FONT_16X16_NUM_IMAGES   96

#define CAPS_SX 10
#define LOWER_SX 9
#define TEXT_SY 16
		//	Format:
		//	U,V,Width,Height

extern const unsigned int font_16x16_texcoords[] = {
	0, 0, 4, TEXT_SY, /*   */
	16, 0, 5, TEXT_SY, /* ! */
	32, 0, 6, TEXT_SY, /* " */
	48, 0, 9, TEXT_SY, /* # */
	0, 16, 9, TEXT_SY, /* $ */
	16, 16, 14, TEXT_SY, /* % */
	32, 16, 9, TEXT_SY, /* £ */
	48, 16, 3, TEXT_SY, /* ' */
	0, 32, 5, TEXT_SY, /* ( */
	16, 32, 5, TEXT_SY, /* ) */
	32, 32, 5, TEXT_SY, /* ´ */
	48, 32, 9, TEXT_SY, /* + */
	0, 48, 4, TEXT_SY, /* , */
	16, 48, 5, TEXT_SY, /* - */
	32, 48, 4, TEXT_SY, /* . */
	48, 48, 4, TEXT_SY, /* / */
	0, 64, 9, TEXT_SY, /* 0 */
	16, 64, 9, TEXT_SY, /* 1 */
	32, 64, 9, TEXT_SY, /* 2 */
	48, 64, 9, TEXT_SY, /* 3 */
	0, 80, 9, TEXT_SY, /* 4 */
	16, 80, 9, TEXT_SY, /* 5 */
	32, 80, 9, TEXT_SY, /* 6 */
	48, 80, 9, TEXT_SY, /* 7 */
	0, 96, 9, TEXT_SY, /* 8 */
	16, 96, 9, TEXT_SY, /* 9 */
	32, 96, 4, TEXT_SY, /* : */
	48, 96, 4, TEXT_SY, /* ; */
	0, 112, 9, TEXT_SY, /* < */
	16, 112, 9, TEXT_SY, /* = */
	32, 112, 9, TEXT_SY, /* > */
	48, 112, 9, TEXT_SY, /* ? */
	0, 128, 16, TEXT_SY, /* @ */
	16, 128, 11, TEXT_SY, /* A */
	32, 128, 11, TEXT_SY, /* B */
	48, 128, 12, TEXT_SY, /* C */
	0, 144, 12, TEXT_SY, /* D */
	16, 144, 11, TEXT_SY, /* E */
	32, 144, 10, TEXT_SY, /* F */
	48, 144, 12, TEXT_SY, /* G */
	0, 160, 11, TEXT_SY, /* H */
	16, 160, 3, TEXT_SY, /* I */
	32, 160, 8, TEXT_SY, /* J */
	48, 160, 11, TEXT_SY, /* K */
	0, 176, 9, TEXT_SY, /* L */
	16, 176, 13, TEXT_SY, /* M */
	32, 176, 11, TEXT_SY, /* N */
	48, 176, 12, TEXT_SY, /* O */
	0, 192, 11, TEXT_SY, /* P */
	16, 192, 12, TEXT_SY, /* Q */
	32, 192, 11, TEXT_SY, /* R */
	48, 192, 11, TEXT_SY, /* S */
	0, 208, 9, TEXT_SY, /* T */
	16, 208, 11, TEXT_SY, /* U */
	32, 208, 11, TEXT_SY, /* V */
	48, 208, 15, TEXT_SY, /* W */
	0, 224, 11, TEXT_SY, /* X */
	16, 224, 9, TEXT_SY, /* Y */
	32, 224, 9, TEXT_SY, /* Z */
	48, 224, 4, TEXT_SY, /* [ */
	0, 240, 4, TEXT_SY, /* \ */
	16, 240, 4, TEXT_SY, /* ] */
	32, 240, 7, TEXT_SY, /* ^ */
	48, 240, 9, TEXT_SY, /* _ */
	0, 256, 5, TEXT_SY, /* ` */
	16, 256, 9, TEXT_SY, /* a */
	32, 256, 9, TEXT_SY, /* b */
	48, 256, 8, TEXT_SY, /* c */
	0, 272, 9, TEXT_SY, /* d */
	16, 272, 9, TEXT_SY, /* e */
	32, 272, 4, TEXT_SY, /* f */
	48, 272, 9, TEXT_SY, /* g */
	0, 288, 8, TEXT_SY, /* h */
	16, 288, 4, TEXT_SY, /* i */
	32, 288, 3, TEXT_SY, /* j */
	48, 288, 8, TEXT_SY, /* k */
	0, 304, 3, TEXT_SY, /* l */
	16, 304, 13, TEXT_SY, /* m */
	32, 304, 8, TEXT_SY, /* n */
	48, 304, 9, TEXT_SY, /* o */
	0, 320, 9, TEXT_SY, /* p */
	16, 320, 9, TEXT_SY, /* q */
	32, 320, 5, TEXT_SY, /* r */
	48, 320, 8, TEXT_SY, /* s */
	0, 336, 4, TEXT_SY, /* t */
	16, 336, 8, TEXT_SY, /* u */
	32, 336, 7, TEXT_SY, /* v */
	48, 336, 11, TEXT_SY, /* w */
	0, 352, 7, TEXT_SY, /* x */
	16, 352, 7, TEXT_SY, /* y */
	32, 352, 7, TEXT_SY, /* z */
	48, 352, 5, TEXT_SY, /* { */
	0, 368, 3, TEXT_SY, /* | */
	16, 368, 5, TEXT_SY, /* } */
	32, 368, 9, TEXT_SY, /* ~ */
	48, 368, 12, TEXT_SY, /*  */
	0, 384, 9, TEXT_SY, /* € */
	16, 384, 12, TEXT_SY, /* � */
	32, 384, 4, TEXT_SY, /* ‚ */
	48, 384, 9, TEXT_SY, /* ƒ */
	0, 400, 5, TEXT_SY, /* „ */
	16, 400, 16, TEXT_SY, /* … */
	32, 400, 9, TEXT_SY, /* † */
	48, 400, 9, TEXT_SY, /* ‡ */
	0, 416, 5, TEXT_SY, /* ˆ */
	16, 416, 17, TEXT_SY, /* ‰ */
	32, 416, 11, TEXT_SY, /* Š */
	48, 416, 5, TEXT_SY, /* ‹ */
	0, 432, 17, TEXT_SY, /* Œ */
	16, 432, 12, TEXT_SY, /* � */
	32, 432, 9, TEXT_SY, /* Ž */
	48, 432, 12, TEXT_SY, /* � */
	0, 448, 12, TEXT_SY, /* � */
	16, 448, 4, TEXT_SY, /* ‘ */
	32, 448, 4, TEXT_SY, /* ’ */
	48, 448, 5, TEXT_SY, /* “ */
	0, 464, 5, TEXT_SY, /* ” */
	16, 464, 6, TEXT_SY, /* • */
	32, 464, 9, TEXT_SY, /* – */
	48, 464, 16, TEXT_SY, /* — */
	0, 480, 4, TEXT_SY, /* ˜ */
	16, 480, 16, TEXT_SY, /* ™ */
	32, 480, 8, TEXT_SY, /* š */
	48, 480, 5, TEXT_SY, /* › */
	0, 496, 15, TEXT_SY, /* œ */
	16, 496, 12, TEXT_SY, /* � */
	32, 496, 7, TEXT_SY, /* ž */
	48, 496, 9, TEXT_SY, /* Ÿ */
};
#endif